### ISSUE TITLE
Current ToDo List

### ISSUE THREAD

**Issue by Wouter-J** [survivorbat/IVT2.2-MEAN-Groepsproject#1]
- [x] Form validatie zodat lege berichten niet gestuurd kunnen worden
- [x] Resource lijst
- [x] UI fixen voor messages
- [x] Als een nieuwe resource toegevoegd wordt moet deze niet gedupliceerd worden als er al een in zit

**Tests**
- [x] chatbox
- [x] chatmessage
- [x] user
- [x] chatresource
